export const GET_SETTINGS = "GET_SETTINGS"
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS"
export const GET_SETTINGS_FAIL = "GET_SETTINGS_FAIL"

export const ADD_SETTINGS = "ADD_SETTINGS"
export const ADD_SETTINGS_SUCCESS = "ADD_SETTINGS_SUCCESS"
export const ADD_SETTINGS_FAIL = "ADD_SETTINGS_FAIL"

export const UPDATE_SETTINGS = "UPDATE_SETTINGS"
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS"
export const UPDATE_SETTINGS_FAIL = "UPDATE_SETTINGS_FAIL"

export const DELETE_SETTINGS = "DELETE_SETTINGS"
export const DELETE_SETTINGS_SUCCESS = "DELETE_SETTINGS_SUCCESS"
export const DELETE_SETTINGS_FAIL = "DELETE_SETTINGS_FAIL"

export const SET_SETTINGS_FIELD_ERRORS = "SET_SETTINGS_FIELD_ERRORS"
